In [1]:
import numpy as np
import knn

In [2]:
knn.img2vector('data/ch02/trainingDigits/0_0.txt')

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [3]:
testvec = knn.img2vector('data/ch02/trainingDigits/0_13.txt')
testvec[0,0:31]

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.])

In [4]:
testvec[0,32:63]

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        1.,  1.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.])

In [12]:
dirname = 'data/ch02/trainingDigits'

In [13]:
reload(knn)
knn.handwritingClassTest(3)

5_42.txt: class sb 5 is 3
3_11.txt: class sb 3 is 9
9_68.txt: class sb 9 is 5
5_43.txt: class sb 5 is 6
9_60.txt: class sb 9 is 7
8_45.txt: class sb 8 is 1
3_55.txt: class sb 3 is 9
8_11.txt: class sb 8 is 6
1_86.txt: class sb 1 is 7
8_36.txt: class sb 8 is 1
8_23.txt: class sb 8 is 3
9_14.txt: class sb 9 is 1


(12, 0.012684989429175475)

In [14]:
knn.handwritingClassTest(2)

5_42.txt: class sb 5 is 3
3_11.txt: class sb 3 is 9
5_43.txt: class sb 5 is 4
8_45.txt: class sb 8 is 1
3_46.txt: class sb 3 is 2
8_11.txt: class sb 8 is 6
3_42.txt: class sb 3 is 8
4_2.txt: class sb 4 is 9
8_36.txt: class sb 8 is 1
8_23.txt: class sb 8 is 3
3_43.txt: class sb 3 is 2
3_49.txt: class sb 3 is 8
5_33.txt: class sb 5 is 9


(13, 0.013742071881606765)

In [15]:
knn.handwritingClassTest(5)

5_42.txt: class sb 5 is 3
3_11.txt: class sb 3 is 9
9_68.txt: class sb 9 is 5
5_43.txt: class sb 5 is 4
9_60.txt: class sb 9 is 7
8_45.txt: class sb 8 is 1
3_55.txt: class sb 3 is 9
8_11.txt: class sb 8 is 6
4_46.txt: class sb 4 is 0
8_35.txt: class sb 8 is 1
1_86.txt: class sb 1 is 7
8_36.txt: class sb 8 is 1
8_23.txt: class sb 8 is 3
8_8.txt: class sb 8 is 3
9_14.txt: class sb 9 is 1
8_68.txt: class sb 8 is 1
3_49.txt: class sb 3 is 8
5_33.txt: class sb 5 is 9


(18, 0.019027484143763214)